name: isar_reproduce
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  # 数据库
  isar: 3.0.1
  isar_flutter_libs: 3.0.1
  path_provider: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  isar_generator: 3.0.1
  build_runner: any

flutter:
  uses-material-design: true
  assets:
    - assets/